// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvF2v9huaGomG8jz9b5lXqddk4Ub6hAfg',
    appId: '1:329296732142:web:b94ff7e82f0ba5ddd8b8ff',
    messagingSenderId: '329296732142',
    projectId: 'mobliedev',
    authDomain: 'mobliedev.firebaseapp.com',
    storageBucket: 'mobliedev.firebasestorage.app',
    measurementId: 'G-4WLRJMK05C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk87TFnFPOO8ZLl3cfvdSWjuV07Hn1_l8',
    appId: '1:329296732142:android:847df759a942ccbed8b8ff',
    messagingSenderId: '329296732142',
    projectId: 'mobliedev',
    storageBucket: 'mobliedev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxriLD-PYHyKV3jNeVlL9BiBpPYXIjn0U',
    appId: '1:329296732142:ios:ec3b0d1d616800e3d8b8ff',
    messagingSenderId: '329296732142',
    projectId: 'mobliedev',
    storageBucket: 'mobliedev.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxriLD-PYHyKV3jNeVlL9BiBpPYXIjn0U',
    appId: '1:329296732142:ios:ec3b0d1d616800e3d8b8ff',
    messagingSenderId: '329296732142',
    projectId: 'mobliedev',
    storageBucket: 'mobliedev.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvF2v9huaGomG8jz9b5lXqddk4Ub6hAfg',
    appId: '1:329296732142:web:b9910bbc455666c8d8b8ff',
    messagingSenderId: '329296732142',
    projectId: 'mobliedev',
    authDomain: 'mobliedev.firebaseapp.com',
    storageBucket: 'mobliedev.firebasestorage.app',
    measurementId: 'G-XZE8LF02QV',
  );
}
